env            = "dev"
aws_region     = "eu-west-2"
base_url       = "https://dev.example.com"
environment    = "dev"
project_name   = "url-shortener"
log_bucket_arn = "arn:aws:s3:::url-shortener-waf-logs-dev"
jwt_secret     = "your-jwt-secret-here"