env            = "prod"
aws_region     = "eu-west-2"
base_url       = "https://short.example.com"
environment    = "prod"
project_name   = "url-shortener"
log_bucket_arn = "arn:aws:s3:::url-shortener-waf-logs-prod"
jwt_secret     = "your-jwt-secret-here"
