name: Deploy URL Shortener

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1        // we can variabilise this as well based on the environment.
    
    # -------- BUILD LAMBDA --------    
    - name: Build Lambda
      run: |
        cd lambda
        npm install
        zip -r ../terraform/lambda.zip .
   
    # -------- LINT --------
    - name: Terraform Format Check
    run: terraform fmt -check -recursive
    working-directory: terraform

   # -------- VALIDATE --------
    - name: Terraform Validate
    run: terraform validate
    working-directory: terraform

   # -------- INIT --------
    - name: Terraform Init
      run: terraform init
      working-directory: terraform

      # -------- PLAN --------
    - name: Terraform Plan
      run: terraform plan -var-file=env/dev.tfvars
      working-directory: terraform

      # -------- APPLY --------
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve -var-file=env/prod.tfvars
      working-directory: terraform
